language: python
matrix:
    fast_finish: true
    include:
        - { python: "3.7", dist: xenial, sudo: true }
before_install:
  - sudo apt update; sudo apt install libsdl2-dev
install: pip install '.[dev]'
script:
    - make ci
notifications:
  email:
    on_success: change
    on_failure: change
