language: python
matrix:
    fast_finish: true
    include:
      - python: "3.7"
        dist: xenial
        sudo: true
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
              - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
                key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            packages:
              - libclang-7-dev
before_install:
  - sudo apt update; sudo apt install libsdl2-dev
install: pip install '.[dev]'
script:
    - make ci
notifications:
  email:
    on_success: change
    on_failure: change
